### ISSUE TITLE
otlp*http modules import grpc

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2579]
### Description

This was surfaced in the discussion:https://github.com/open-telemetry/opentelemetry-go/discussions/2509 

The otlptracehttp client and otlptrace depend on grpc.  This is a transitive dependency from internal/otlpconfig.  This is counter to why we split these packages into separate mods in the first place.

### Environment

- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.15]
- opentelemetry-go version: [e.g. v0.14.0, 3c7face]

### Steps To Reproduce

1. `cd exporters/otlp/otlptrace/otlptracehttp` 
2.  `go mod graph | grep grpc`  this should be empty
3. `go mod why google.golang.org/grpc`  this should report that module does not need grpc.

### Expected behavior

The HTTP client should not depend on grpc.

### Aditional information
`otlpconfig` has a config struct that is shared between HTTP client and grpc.  This has logic around extracting the variables from the environment.  Because the config has settings for grpc this means importing `otlpconfig` will import grpc (even if they are later pruned).

**Comment by MadVikingGod** [comment]
I dug into this and I don't think we can avoid this.

This is because the opentelemetry-proto-go only defines the services and the request message with the grpc service.  So for us to make HTTP separate from GRPC the [service request message](https://github.com/open-telemetry/opentelemetry-proto/blob/f8c59fe6b063397714034d9727f08aca1a5b99b3/opentelemetry/proto/collector/trace/v1/trace_service.proto#L35) would need to be moved.

**Comment by MrAlias** [comment]
> I dug into this and I don't think we can avoid this.

Should this issue be closed?

**Comment by MadVikingGod** [comment]
I would close this if either we don't think we will ever change how the grpc is generated, or if we decide that this isn't a goal.

If the former, we should put an issue into proto-go to address this.
For the latter, I think we should make an issue to reduce the mods we have in the `otlptrace` directory.  If you will have the grpc imported no matter what I don't see the need to break HTTP vs grpc.

**Comment by utezduyar** [comment]
I will move what I have written on the Slack here. Thanks to Damien who has informed me about this. 

grpc/protobuf dependency is bringing in lots of packages and increasing the size tremendously for a simple hello world application. Due to this SDK becomes unreasonable for constraint environments. 

I have a helloworld application instrumented with the API layer. When I link it with the SDK layer, the size is going off the charts. I compiled the application with `go build -ldflags="-s -w"`
The SDK is using console `exporter, otlphttp exporter, resources, semconv`.
```
2.9M Feb 24 07:44 main.api
11M Feb 24 07:45 main.sdk
```
It is almost 8MB difference. I profiled both applications with `goweight` and the top list is for grpc and protobuf stuff.
```
5.8 MB [google.golang.org/protobuf/internal/impl](http://google.golang.org/protobuf/internal/impl)
4.0 MB [golang.org/x/net/http2](http://golang.org/x/net/http2)
3.2 MB [google.golang.org/grpc](http://google.golang.org/grpc)
2.4 MB [google.golang.org/grpc/internal/transport](http://google.golang.org/grpc/internal/transport)
2.3 MB [google.golang.org/protobuf/internal/filedesc](http://google.golang.org/protobuf/internal/filedesc)
1.9 MB [golang.org/x/sys/unix](http://golang.org/x/sys/unix)
1.5 MB [github.com/grpc-ecosystem/grpc-gateway/v2/runtime](http://github.com/grpc-ecosystem/grpc-gateway/v2/runtime)
1.4 MB text/template/parse
1.4 MB text/template
1.3 MB [go.opentelemetry.io/otel/sdk/trace](http://go.opentelemetry.io/otel/sdk/trace)
1.3 MB [google.golang.org/protobuf/reflect/protoreflect](http://google.golang.org/protobuf/reflect/protoreflect)
1.3 MB [google.golang.org/protobuf/types/descriptorpb](http://google.golang.org/protobuf/types/descriptorpb)
1.2 MB encoding/xml
1.2 MB [github.com/golang/protobuf/proto](http://github.com/golang/protobuf/proto)
1.1 MB html/template
1.1 MB [google.golang.org/protobuf/encoding/protojson](http://google.golang.org/protobuf/encoding/protojson)
994 kB [google.golang.org/protobuf/reflect/protodesc](http://google.golang.org/protobuf/reflect/protodesc)
945 kB [golang.org/x/text/unicode/norm](http://golang.org/x/text/unicode/norm)
```
I don’t understand why grpc/protobuf dependencies need to be linked in. Am I missing a configuration or is there a bug in bringing in dependencies. Let me know if you want to see the helloworld application. (edited)

Exporters are

**Comment by pellared** [comment]
@utezduyar protobuf dependencies are needed as `otlptracehttp` is basically profobuf over HTTP. The issue is that gRPC dependencies should not be present.

**Comment by utezduyar** [comment]
@pellared I am a bit confused. I WireSharked my application and it posted the trace data as JSON to /v1/traces of my local collector. Where is the protobuf then?

**Comment by pellared** [comment]
@utezduyar The payload send via HTTP is serialized using [protobuf](https://protobuf.dev/) .

**Comment by utezduyar** [comment]
I figured it out. It is the resource information that is posted as json but you are right, I saw the posts as application/x-protobuf on WireShark. Thanks for clarifying.

**Comment by utezduyar** [comment]
@MadVikingGod Are your findings from 1 year ago still valid? If so, is it a complex tax to move the service request message?

**Comment by MrAlias** [comment]
> @MadVikingGod Are your findings from 1 year ago still valid? If so, is it a complex tax to move the service request message?

Moving the service request is almost certainly not something the [proto team](https://github.com/open-telemetry/opentelemetry-proto) want to do, but ultimately it is question for them.

**Comment by utezduyar** [comment]
I am not really understanding the problem or the discussion of moving or not due to my lack of decent understanding of the internals (yet at least). 
Can service request message not be duplicated instead of moving?
If the service request message is requiring grpc, how is HTTP 1.1 trace export going to work?
I checked C++ SDK and they don't have this dependency. What is really different with go?

**Comment by utezduyar** [comment]
@MrAlias I looked at it a bit more and I think I understand it better. I still think my questions are valid regarding for example how C++ can handle it but not go. Anyways. 
I am trying to figure out if this is not something it can be solved in the https://github.com/open-telemetry/opentelemetry-proto-go by having 2 generated code for the trace service, one with GRPC one without, as separate modules. Opinion?

**Comment by MrAlias** [comment]
`go mod why` will show a shortest path in the import graph from the main module, it does not show all.

There have been prior attempts to separate `otlpconfig` to address this. Ultimately, it will not address the issue because `go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp` [imports `go.opentelemetry.io/proto/otlp`](https://github.com/open-telemetry/opentelemetry-go/blob/3df561e6446d5990db4aed37ab9c0a7a1ceadfce/exporters/otlp/otlptrace/otlptracehttp/go.mod#L12) and `go.opentelemetry.io/proto/otlp` [imports `google.golang.org/grpc`](https://github.com/open-telemetry/opentelemetry-proto-go/blob/0cb32f1c7e7c97b4da04beb087ad5221ca31ffd2/otlp/go.mod#LL7C2-L7C24). There still exists an indirect dependency on `go.opentelemetry.io/proto/otlp` after `otlpconfig` was split.

**Comment by utezduyar** [comment]
I wanted to see what more things are dependent on grpc and experimented. otlpconfig and proto modules as we discussed before are the only dependencies. 

otlpconfig split: go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig/options.go: Removed all the mentions of grpc (for the sake of moving foward).

proto files: go.opentelemetry.io/proto/otlp/otlp/collector/trace/v1: I deleted both the service and the gateway files (trace_service.pb.gw.go and trace_service_grpc.pb.go). 

This way, grpc dependency was dropped and my binary size was down 20%.

I would like to discuss the possibility of splitting service and gateway files in a separate module to get around go compiler downside. Some contributors in this issue are also committers in opentelemetry-proto-go. What is the best way to discuss this topic with opentelemetry-proto-go?

**Comment by MrAlias** [comment]
> I would like to discuss the possibility of splitting service and gateway files in a separate module to get around go compiler downside. Some contributors in this issue are also committers in opentelemetry-proto-go. What is the best way to discuss this topic with opentelemetry-proto-go?

Can you provide a proposal for how `go.opentelemetry.io/proto/otlp` will be changed and how the [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go) will be updated to support the changes?

**Comment by utezduyar** [comment]
I think the protobuf definition is already good enough and the code generator is doing it's best at splitting code based on different use cases. Therefore I do NOT believe we need a change from the go.opentelemetry.io/proto/otlp repo. 

The `collector/` under the [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go) is having 3 logical go file separation for 3 telemetry types. One file for the data type, one file for the grpc client and one file for the grpc server. 

My propose is to have grpc client and grpc server into it's own module in the [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go) repo. 

Again, if the go linker could have been able to figure out that it does not need to link the grpc libraries because the code is not used, we wouldn't need to break the generated go files.

**Comment by MrAlias** [comment]
> The `collector/` under the [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go) is having 3 logical go file separation for 3 telemetry types. One file for the data type, one file for the grpc client and one file for the grpc server.
> 
> My propose is to have grpc client and grpc server into it's own module in the [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go) repo.

Your proposal is to duplicate the code in `go.opentelemetry.io/proto/otlp` into new modules? This is not a clear solution to me.

**Comment by utezduyar** [comment]
Not duplicate but split the files in the `collector/`. `https://github.com/open-telemetry/opentelemetry-proto-go/tree/main/otlp/collector/trace/v1` `https://github.com/open-telemetry/opentelemetry-proto-go/tree/main/otlp/collector/metrics/v1` and `https://github.com/open-telemetry/opentelemetry-proto-go/tree/main/otlp/collector/logs/v1`. 

Let's take the tracing as example: 
Module 1: `https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/otlp/collector/trace/v1/trace_service.pb.go`
Module 2: `https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/otlp/collector/trace/v1/trace_service.pb.gw.go` and `https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/otlp/collector/trace/v1/trace_service_grpc.pb.go`

**Comment by MrAlias** [comment]
> Let's take the tracing as example: Module 1: `https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/otlp/collector/trace/v1/trace_service.pb.go` Module 2: `https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/otlp/collector/trace/v1/trace_service.pb.gw.go` and `https://github.com/open-telemetry/opentelemetry-proto-go/blob/main/otlp/collector/trace/v1/trace_service_grpc.pb.go`

How do you plan to split `go.opentelemetry.io/proto/otlp/collector/trace` and have two packages with exactly the same package name? Modules are not split by files, they are split by directories.

If you move something out of `go.opentelemetry.io/proto/otlp/collector` it will be a breaking change to the exiting package. This will be backwards incompatible.

**Comment by utezduyar** [comment]
I see your point. If we cannot break backwards compatibility, then not sure what options we have left but to duplicate `go.opentelemetry.io/proto/otlp` into new modules. 
It is not going to help to make changes in the proto files since all the generated code goes into one module, `go.opentelemetry.io/proto/otlp`, that the linker is going to pick up grpc code, even when they are unused.

**Comment by dmathieu** [comment]
Does this have a known performance impact, or is it about disk space?

**Comment by utezduyar** [comment]
> I would close this if either we don't think we will ever change how the grpc is generated, or if we decide that this isn't a goal.
> 
> If the former, we should put an issue into proto-go to address this. For the latter, I think we should make an issue to reduce the mods we have in the `otlptrace` directory. If you will have the grpc imported no matter what I don't see the need to break HTTP vs grpc.

Even after 1 year, I believe @MadVikingGod 's comments are still relevant (sorry, it took me a while to come to the same point). I have created an issue in the opentelemetry-proto-go repo (above). 

If we would like to solve this issue, I cannot come up with a better plan than below. 
A) Split proto-go files in modules in a backwards incompatible way and publish both major versions. 
B) Work on the internal/otlpconfig to split grpc dependencies. 

If we don't want to split the dependencies, then maybe we should close this ticket and open a new one to reduce the mods in the `otlptrace`

The last option is to mark the ticket as we will not make any change. If we pick this option, I am considering to carry a downstream patch that removes the grpc dependencies and use the patch.

**Comment by MrAlias** [comment]
The [`slim/otlp`](https://pkg.go.dev/go.opentelemetry.io/proto/slim/otlp) module was just released. This issue should be resolvable now.

**Comment by utezduyar** [comment]
Huge thanks @pellared for this. I cannot wait to test it to see that the binary size has gone down a lot.

**Comment by pellared** [comment]
@utezduyar, I will try to get it done for next release.

**Comment by pellared** [comment]
Unfortunately, it is not possible (without making a breaking change) to remove the grpc dependency in `otlptracehttp` because of https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#NewClient (https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace#Client exposes the proto types).

The fix would require creating v2 modules. For `oteltracehttp` and `oteltracegrpc`. After these are created we still need to support the v1 modules for at least a year.

More: https://github.com/open-telemetry/opentelemetry-go/pull/5221

**Comment by MrAlias** [comment]
@pellared are you planning to split the otlptracehttp work to its own issue so we can close this with #5222?

**Comment by pellared** [comment]
> @pellared are you planning to split the otlptracehttp work to its own issue so we can close this with #5222?

Done:
- https://github.com/open-telemetry/opentelemetry-go/issues/5247
- https://github.com/open-telemetry/opentelemetry-go/issues/5248

**Comment by pellared** [comment]
Fixed for metrics

**Comment by gregoryfranklin** [comment]
FYI. it looks like its no longer possible to have both otelmetrichttp and otelmetricgrpc in the same binary.  I'm not sure how common this is, but go.opentelemetry.io/contrib/exporters/autoexport is an example.

```
$ git clone https://github.com/open-telemetry/opentelemetry-go-contrib.git
$ cd opentelemetry-go-contrib/exporters/autoexport/
$ go get go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp@main
go: upgraded go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.25.0 => v1.25.1-0.20240422142149-b34cfc47c4e0
go: added go.opentelemetry.io/proto/slim/otlp v1.2.0
$ go get go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@main
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.25.1-0.20240422142149-b34cfc47c4e0
go: upgraded go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.25.0 => v1.25.1-0.20240422142149-b34cfc47c4e0
$ go test ./...
panic: proto: file "opentelemetry/proto/common/v1/common.proto" is already registered
	previously from: "go.opentelemetry.io/proto/otlp/common/v1"
	currently from:  "go.opentelemetry.io/proto/slim/otlp/common/v1"
See https://protobuf.dev/reference/go/faq#namespace-conflict
```

**Comment by pellared** [comment]
He had to revert the changes because of https://github.com/open-telemetry/opentelemetry-go/issues/5251

**Comment by dmathieu** [comment]
Could this be fixed with a v2 of proto-go where the protobufs wouldn't be in a slim package, but always in separate packages from the grpc service?

**Comment by pellared** [comment]
AFAIU it won't help as as they will still have the same "file descriptors".

**Comment by XSAM** [comment]
Removing this out of the `v1.26.0` milestone

**Comment by pellared** [comment]
To fix it we would need a fix in https://github.com/golang/protobuf and probably in protoc generation as well.

**Comment by qianlongzt** [comment]
I made a protoc plugin to generate a file that imports the slim package definition.

This should solve the error:`proto: file "opentelemetry/proto/common/v1/common.proto" is already registered."`
https://github.com/open-telemetry/opentelemetry-proto-go/pull/237/files#diff-bbb70f56aa8a1c7990c0c7137d98c81fd614b5ae1078ba145d3fa9ef5b89a701

**Comment by pellared** [comment]
@qianlongzt, thanks a lot. I will look at this once I have more time (expect weeks, not days 😬 ).

**Comment by pellared** [comment]
@qianlongzt, it would be good if you provide more details how your solution works. Personally, I am worried about the maintainability and trustworthiness of [this](https://github.com/open-telemetry/build-tools/pull/383) protoc plugin. Who would maintain it? Wouldn't the solution cause some issues in some edge cases?

**Comment by qianlongzt** [comment]
There are three types of files: `pb.go`, `_grpc.pb.go` and `pb.gw.go`.

I just add references to any Go public items, like message, enum, oneOf, using Go type aliases and constants in the Protoc plugin. I don't fully understand the output of `protoc-gen-go`, and it may change in the future. Using a Go lexer/parser might be a better choice.

To reduce maintenance overhead, we should reorganize the code, remove any duplicate generation of `pb.go`, and find a place to define gRPC-related messages, like `xxxReq` and `xxxRsp`. The gRPC messages shim can be manually maintained.

```go
package v1

import slim "go.opentelemetry.io/proto/slim/otlp/collector/logs/v1"

type ExportLogsServiceRequest = slim.ExportLogsServiceRequest
type ExportLogsServiceResponse = slim.ExportLogsServiceResponse
```

**Comment by XSAM** [comment]
@qianlongzt, thanks for the work. IIUC, your changes are:

- Move all protobuf messages to the `slim` package (including grpc-related messages, like `ExportLogsServiceRequest`, as OTLP HTTP would need this)
- Leave gRPC interfaces, like `LogsServiceServer`, untouched in the `otlp/collector`.
- Replace old types from protobuf messages with types linked from `slim`, like having `type ExportLogsServiceRequest = slim.ExportLogsServiceRequest` in the `otlp/collector/logs/v1` package.

This is the approach mentioned in https://github.com/open-telemetry/opentelemetry-go/issues/2579#issuecomment-2072854539.

---

I ran an experiment:

Server (using https://github.com/open-telemetry/opentelemetry-proto-go/pull/237):

```go
package main

import (
	"context"
	logs "go.opentelemetry.io/proto/otlp/collector/logs/v1"
	"google.golang.org/grpc"
	"log"
	"net"

	slimlogs "go.opentelemetry.io/proto/slim/otlp/collector/logs/v1"
)

type server struct {
	logs.LogsServiceServer
}

func (server) Export(context.Context, *slimlogs.ExportLogsServiceRequest) (*slimlogs.ExportLogsServiceResponse, error) {
	log.Println("Export called")
	return &slimlogs.ExportLogsServiceResponse{}, nil
}

func main() {
	lis, err := net.Listen("tcp", "localhost:4317")
	if err != nil {
		panic(err)
	}

	grpcServer := grpc.NewServer()
	logs.RegisterLogsServiceServer(grpcServer, server{})

	err = grpcServer.Serve(lis)
	if err != nil {
		panic(err)
	}
}
```

Client (using normal implementation)

```go
package main

import (
	"context"
	"go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc"
	logapi "go.opentelemetry.io/otel/log"
	"go.opentelemetry.io/otel/sdk/log"
)

func main() {
	exporter, err := otlploggrpc.New(context.Background(), otlploggrpc.WithInsecure(), otlploggrpc.WithEndpoint("localhost:4317"))
	if err != nil {
		panic(err)
	}

	processor := log.NewBatchProcessor(exporter)
	provider := log.NewLoggerProvider(
		log.WithProcessor(processor),
	)

	logger := provider.Logger("example")
	logger.Emit(context.Background(), logapi.Record{})
}
```

This change can pass the gRPC calling from other OTLP clients that are not using this proto implementation.

Though, I have the following concerns:

- This is a breaking change for the current otlp v1, as the concrete types from non-slim packages have changed.
- For v2
  - We need to change the `GoPackagePath` value: https://github.com/open-telemetry/opentelemetry-proto-go/blob/a24b10178879fb480eeb6687cb19c2b926c53f83/slim/otlp/trace/v1/trace.pb.go#L1268. I am not sure it could occur any compatible issue or not.
  - We are not using the default file structure from `protoc`. Thus, compatible issue concerns.
- I don't know if this is the best place to hold and maintain a `protoc` plugin. Instead of hosting it, bringing it upstream seems more appropriate.

**Comment by qianlongzt** [comment]
@pellared @XSAM

I updated my attempt:

1. Introduced a new otelgrpc module and moved all gRPC-related code (grpc.pb.go, pb.gw.go) to this new module.
   1. This is a breaking change for otelv1.
2. Removed the slim module, which existed to remove the gRPC dependency.
3. No need for the protoc-plugin anymore.

Users who need gRPC should update to the new otelgrpc module.

https://github.com/open-telemetry/opentelemetry-proto-go/pull/248/files

**Comment by XSAM** [comment]
@qianlongzt, thanks for the update. This looks better than before.

Let me summarize your changes so other maintainers can catch up quickly: basically, you separate the proto-generating process into two parts. One only generates proto messages (including grpc message), and the other only generates grpc service in a new package. Then, manually create `shim.go` to create an alias type of grpc messages in the grpc service package.

My only concern is still the compatibility issue, as we changed the default protobuf generated folder structure. I am not familiar with the situation when the default folder structure is changed. Do you mind creating an issue to https://github.com/golang/protobuf about this so we can get opinions from the protobuf community?

**Comment by pellared** [comment]
@qianlongzt, bump

**Comment by qianlongzt** [comment]
Sorry for the late response. I’ve created an issue: https://github.com/grpc/grpc-go/issues/8233

**Comment by nvx** [comment]
I just ran into this, I can understand the gotchas with having the grpc codegen in the same package as the rest of the protos adding complexity, but at least in my `go mod why` output the thing that's popping up first is the otlptracehttp/internal/otlpconfig package, which at a glance looks to be caused by these whcih I'm a little confused to see in the http config

https://github.com/open-telemetry/opentelemetry-go/blob/31dbd0761c8a8a33e59585ad1173bb538f765e46/exporters/otlp/otlptrace/otlptracehttp/internal/otlpconfig/options.go#L75-L76

I see there was an attempt to have a slim proto package which ended up conflicting if someone had both http and grpc exporters due to a conflict in the proto names being the same preventing both pacakges being imported. I'm not sure if a workaround for that was figured out yet, but in my mind at least if RPCs aren't being used, and neither are things like the Any type, then the package name wouldn't affect serialisation, so a copy of the proto under a different package without the rpc stubs could be a viable workaround allowing the http package to just use the proto version. I've seen this trick used with the gRPC health proto messages with ConnectRPC and it seems fine over there.

**Comment by pellared** [comment]
@nvx, can you look at these prototype PRs?
- https://github.com/pellared/opentelemetry-proto-go/pull/1
- https://github.com/pellared/opentelemetry-go/pull/13

**Comment by nvx** [comment]
> [@nvx](https://github.com/nvx), can you look at these prototype PRs?
> 
> * [Prototype: make slim OTLP descriptors coexist with canonical protos pellared/opentelemetry-proto-go#1](https://github.com/pellared/opentelemetry-proto-go/pull/1)
> * [Prototype: remove gRPC from OTLP/HTTP exporters pellared/opentelemetry-go#13](https://github.com/pellared/opentelemetry-go/pull/13)

I'm not super familiar with the otel codebase, but at a glance I can't see any obvious red flags.

**Comment by silverwind** [comment]
+1, I noticed this unused grpc dependency adds 7MB binary size, which I find unacceptably big.
