### ISSUE TITLE
OTLP metric exporter - resource attributes not exported

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-go#3208]
### Description

Resource attributes are not exported using the OTLP metric exporter.

### Environment

- opentelemetry-go version: v0.32.0

### Steps To Reproduce

1. Configure OTLP endpoint
    * OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
2. Run the collector locally with the following config
```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
```
3. Run the following code
```go
package main

import (
	"context"
	"log"
	"time"

	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/metric/global"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"

	semconv "go.opentelemetry.io/otel/semconv/v1.12.0"
)

func main() {
	ctx := context.Background()

	exporter, err := otlpmetricgrpc.New(ctx)
	if err != nil {
		log.Fatalf("%s: %v", "failed to create metric exporter", err)
	}

	reader := metric.NewPeriodicReader(
		exporter,
		metric.WithInterval(2*time.Second),
	)

	res := resource.NewWithAttributes(
		semconv.SchemaURL,

                 // This attribute is not exported
		semconv.ServiceNameKey.String("my-service"),
	)

	meterProvider := metric.NewMeterProvider(
		metric.WithResource(res),
		metric.WithReader(reader),
	)
	global.SetMeterProvider(meterProvider)

	meter := global.Meter("my-meter")

	counter, err := meter.SyncFloat64().Counter("my-counter")
	if err != nil {
		log.Panicf("failed to initialize instrument: %v", err)
	}

	counter.Add(ctx, 12.0)
	time.Sleep(5 * time.Second)
	counter.Add(ctx, 22.0)
	time.Sleep(5 * time.Second)
	counter.Add(ctx, 13.0)

	defer func() {
		err := meterProvider.Shutdown(context.Background())
		if err != nil {
			log.Fatalln(err)
		}
	}()
}
```

4. Output from collector's logging exporter

```shell
2022-09-20T14:31:28.721-0700	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 1}
2022-09-20T14:31:28.722-0700	info	ResourceMetrics #0
Resource SchemaURL: 
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope my-meter 
Metric #0
Descriptor:
     -> Name: my-counter
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
StartTimestamp: 2022-09-20 21:31:26.683813 +0000 UTC
Timestamp: 2022-09-20 21:31:28.685045 +0000 UTC
Value: 12.000000
	{"kind": "exporter", "data_type": "metrics", "name": "logging"}

```

### Expected behavior

Resource should include the attribute `service.name=my-service`

**Comment by MrAlias** [comment]
@alanwest what version of the collector was used in the example?

**Comment by alanwest** [comment]
I built and ran the collector locally from main.

**Comment by MrAlias** [comment]
It looks like `newPipelineRegistries` initializes `pipeline`s without a resource:

https://github.com/open-telemetry/opentelemetry-go/blob/038248b8a2c80ecb0a56fe3ea2a20890126bae98/sdk/metric/pipeline.go#L171

cc @MadVikingGod

**Comment by MrAlias** [comment]
This exists for the `stdoutmetric` exporter as well:

```go
package main

import (
	"context"
	"log"
	"time"

	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"

	semconv "go.opentelemetry.io/otel/semconv/v1.12.0"
)

func main() {
	ctx := context.Background()

	exporter, err := stdoutmetric.New()
	if err != nil {
		log.Fatalf("failed to create metric exporter: %v", err)
	}

	reader := metric.NewPeriodicReader(
		exporter,
		metric.WithInterval(time.Second),
	)

	res := resource.NewWithAttributes(
		semconv.SchemaURL,
		// This attribute is not exported
		semconv.ServiceNameKey.String("my-service"),
	)
	log.Println("resource:", res)

	meterProvider := metric.NewMeterProvider(
		metric.WithResource(res),
		metric.WithReader(reader),
	)
	meter := meterProvider.Meter("my-meter")

	counter, err := meter.SyncFloat64().Counter("my-counter")
	if err != nil {
		log.Fatalf("failed to initialize instrument: %v", err)
	}

	counter.Add(ctx, 12.0)
	time.Sleep(2 * time.Second)

	err = meterProvider.Shutdown(ctx)
	if err != nil {
		log.Fatalln("failed to shutdown", err)
	}
}
```

```go
go 1.19

require (
	go.opentelemetry.io/otel v1.10.0
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.32.0
	go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v0.32.0
	go.opentelemetry.io/otel/sdk v1.10.0
	go.opentelemetry.io/otel/sdk/metric v0.32.0
)

require (
	github.com/cenkalti/backoff/v4 v4.1.3 // indirect
	github.com/go-logr/logr v1.2.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.7.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.10.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric v0.32.0 // indirect
	go.opentelemetry.io/otel/metric v0.32.0 // indirect
	go.opentelemetry.io/otel/trace v1.10.0 // indirect
	go.opentelemetry.io/proto/otlp v0.19.0 // indirect
	golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4 // indirect
	golang.org/x/sys v0.0.0-20210510120138-977fb7262007 // indirect
	golang.org/x/text v0.3.5 // indirect
	google.golang.org/genproto v0.0.0-20211118181313-81c1377c94b1 // indirect
	google.golang.org/grpc v1.46.2 // indirect
	google.golang.org/protobuf v1.28.0 // indirect
)
```

**Comment by MrAlias** [comment]
Validated with the above examples #3218 should resolve this.

**Comment by fracasula** [comment]
I'm still experiencing this on the latest (`main` branch) when I set custom attributes like:

```go
otelRes := resource.NewWithAttributes(
	semconv.SchemaURL,
	semconv.ServiceName("test server"),
	semconv.ServiceVersion("v0.1.0"),
	attribute.String("foo", "bar"), // we expect this to be propagated
)
```

I'm not seeing the "foo=bar" attribute propagated in the metric. I hacked my way through this to solve it but it doesn't feel right, please have a look at [this test](https://github.com/open-telemetry/opentelemetry-go/compare/main...fracasula:opentelemetry-go:fix.resAttrs?expand=1) where I'm replicating the issue.

**Comment by MrAlias** [comment]
@fracasula please open a new bug. The bug described by this issue is still fixed according to the validation it contains.

**Comment by fracasula** [comment]
> @fracasula please open a new bug. The bug described by this issue is still fixed according to the validation it contains.

Done [here](https://github.com/open-telemetry/opentelemetry-go/issues/4098) @MrAlias
